name: Build

on:
  push:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1.2.0
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - run: flutter build appbundle

  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1.2.0
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache:
            true
      - run: flutter build ios --release --no-codesign

  build-web:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1.2.0
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache:
            true
      - run: flutter build web
